on:
  issues:
    types: [opened, reopened]

jobs:
  forking:
    name: 'Test'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Forking
        uses: ./.github/actions
        env:
          jump2header_token: ${{ secrets.JUMP2HEADER_TOKEN }}
      - name: Sleep for 30 seconds
        uses: jakejarvis/wait-action@master
        with:
          time: '30s'
