on:
  issues:
    types: [opened, reopened]

jobs:
  test:
    name: 'Test'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: 'echo "payload: ${{ toJson(github.event) }}"'
      - uses: ./.github/actions
        env:
          jump2header_token: ${{ secrets.JUMP2HEADER_TOKEN }}
